import * as esbuild from "esbuild";
import * as url from "node:url";

await esbuild.build({
    entryPoints: [
        url.fileURLToPath(new URL("../src/watch/livereload/livereload.script.js", import.meta.url)),
    ],
    outfile: url.fileURLToPath(
        new URL("../src/watch/livereload/livereload.script.min.js", import.meta.url),
    ),
    bundle: true,
    minify: true,
    target: "es6",
    define: {
        "import.meta.main": "true",
    },
    banner: {
        js: '/* this file was autogenerated from "livereload.script.ts", do not edit */',
    },
});
