#!/bin/bash

function test {
    deno test --config deno.json --import-map=./import_map.json --allow-read=. --allow-write=. 
}

function fmt {
    deno fmt --config deno.json
}

function example {
    deno --unstable run --import-map=./import_map.json --config deno.json --allow-read=. --allow-write=. --allow-net=deno.land,esm.sh,cdn.esm.sh examples/$1/mod.ts
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %2R s"
time ${@}
