const version = '1.2.172';
const wasmFile = 'swc.wasm';

const swcWasmWeb = await fetch(
    `https://cdn.esm.sh/@swc/wasm-web@${version}/wasm-web_bg.wasm`,
);

const buffer = await swcWasmWeb.arrayBuffer();

await Deno.writeFile(
    new URL(wasmFile, import.meta.url),
    new Uint8Array(buffer),
);

const source =
    `// this file was generated by the \`./cache.ts\` module. Do not change it.
import initSwc from "https://esm.sh/@swc/wasm-web@${version}";

await initSwc(new URL('${wasmFile}', import.meta.url))

export * from "https://esm.sh/@swc/wasm-web@${version}";
export type {
    ExportAllDeclaration,
    ExportNamedDeclaration,
    ImportDeclaration,
    Node,
} from 'https://esm.sh/@swc/core@1.2.171/types.d.ts';    
`;

await Deno.writeTextFile(new URL('mod.ts', import.meta.url), source);
