name: test

on: 
  push:
    branches: dev
  pull_request:
    branches: dev
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: run tests

    strategy:
      matrix:
        deno-version: ["1.33", 1.x, canary]
        include:
          - deno-version: canary
            coverage: true

    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: install deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: run lint
      run: deno lint

    - name: run test
      run: deno task test


    - name: integration test code coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v2
      with: 
        files: ./cov_profile.lcov
        
