name: test

on:
    push:
        branches: dev
    pull_request:
        branches: dev
        types: [opened, synchronize, reopened]

jobs:
    test:
        name: run tests

        strategy:
            matrix:
                node-version: [20.x, 20-v8-canary]
                include:
                    - node-version: 20-v8-canary
                      coverage: true

        runs-on: ubuntu-latest

        env:
            CI: true

        steps:
            - name: checkout project
              uses: actions/checkout@v3

            - name: install node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: run test with coverage
              run: npm run test --workspace=frugal -- --coverage

            - name: integration test code coverage
              if: matrix.coverage
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true
