name: test

on: 
  push:
    branches: dev
  pull_request:
    branches: dev
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: run tests

    strategy:
      matrix:
        deno-version: ["1.30", 1.x, canary]
        include:
          - deno-version: canary
            coverage: true

    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: install deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: install puppeteer
      run: deno run -A --unstable test/install_binaries.ts

    - name: run lint
      run: deno lint

    - name: run test
      run: deno task test

    - name: generate coverage report
      if: matrix.coverage
      run: deno task coverage
      
    - name: unit test code coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v2
      with: 
        files: ./tests/cov_profile/unit/cov_profile.lcov
        flags: unit

    - name: integration test code coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v2
      with: 
        files: ./tests/cov_profile/integration/cov_profile.lcov
        flags: integration
